version: '3.8'
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8082
    depends_on:
      - mysql-docker-container
  mysql-docker-container:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: absa
      MYSQL_USER: simba
      MYSQL_PASSWORD: AppleBank2023#12
      MYSQL_ROOT_PASSWORD: letmein2023#12



